INHERIT: ../en/mkdocs.maybe-insiders.yml
site_name: Logging Discord
site_description: Envie de forma simples e rápida os tracebacks do seu projeto e mensagens de logs para o Discord.

theme:
  name: material
  custom_dir: ../en/docs/
  palette:
    - media: '(prefers-color-scheme: light)'
      scheme: default
      primary: #404eed
      accent: amber
      toggle:
        icon: material/lightbulb
        name: Switch to dark mode
    - media: '(prefers-color-scheme: dark)'
      scheme: slate
      primary: #404eed
      accent: amber
      toggle:
        icon: material/lightbulb-outline
        name: Switch to light mode
  features:
    - search.suggest
    - search.highlight
    - content.tabs.link
    - navigation.indexes
    - content.tooltips
    - navigation.path
    - content.code.annotate
    - content.code.copy
    - content.code.select
  icon:
      repo: fontawesome/brands/github-alt
  logo: /assets/logo.png
  favicon: /assets/favicon.png
  language: pt
#  static_templates:
#    - "404.html"
#    - "sitemap.xml"
#    - "robots.txt"

repo_name: brunobrown/logging-discord
repo_url: https://github.com/brunobrown/logging-discord
edit_uri: /tree/master/docs

plugins:
  macros:
  search:
#  - markdownextradata:
#      data: ../en/data
  mkdocstrings:
    handlers:
      python:
        paths: [ docs/en/mkdocs.yml ]

nav:
#- LoggingDiscord: index.md
- Languages:
  - en: /
  - pt: /pt/

markdown_extensions:
  - attr_list
  - admonition
  - pymdownx.tasklist
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg

extra_css:
  - css/extra.css

extra:
  commands:
    import: from logging_discord import LogDiscord
  analytics:
    provider: google
    property: G-YNEVN69SC3
  social:
    - icon: fontawesome/brands/github-alt
      link: https://github.com/brunobrown/logging-discord
#    - icon: fontawesome/brands/discord
#      link: https://discord.gg/
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/BrunoBrown86
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/bruno-brown-29418167
#    - icon: fontawesome/brands/dev
#      link: https://dev.to/
#    - icon: fontawesome/brands/medium
#      link: https://medium.com/
#    - icon: fontawesome/solid/globe
#      link: https://
  alternate:
    - link: /
      name: en - English
    - link: /pt/
      name: pt - português